# Generated by Django 5.1.3 on 2025-11-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_profile_user"),
        ("course", "0001_initial"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="account.profile",
            ),
        ),
    ]
