# Generated by Django 5.1.3 on 2025-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0002_alter_enrollment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="user_role",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
